import Foundation
import Combine

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    
    @Published var language: String = UserDefaults.standard.string(forKey: "app_lang") ?? "en" {
        didSet { UserDefaults.standard.set(language, forKey: "app_lang") }
    }
    
    private let translations: [String: [String: String]] = [
        "en": [
            "LIBRARY": "LIBRARY",
            "SEARCH": "SEARCH",
            "PLAYER": "PLAYER",
            "EQUALIZER": "EQUALIZER",
            "QUEUE": "QUEUE",
            "ARTISTS": "ARTISTS",
            "MY COLLECTION": "MY COLLECTION",
            "SETTINGS": "SETTINGS",
            "Interface Language": "Language",
            "NOW PLAYING": "NOW PLAYING",
            "LYRICS": "LYRICS",
            "ALBUMS": "ALBUMS",
            "Theme": "Theme",
            "Dark": "Dark",
            "Light": "Light",
            "Parse .cue sheets": "Parse .cue sheets",
            "Search for .lrc lyrics": "Search for .lrc lyrics",
            "Auto-scan on startup": "Auto-scan on startup",
            "Rescan Now": "Rescan Now",
            "Clear Library": "Clear Library",
            "MEDIA FOLDERS": "MEDIA FOLDERS",
            "SCANNING OPTIONS": "SCANNING OPTIONS",
            "MAINTENANCE": "MAINTENANCE",
            "GENERAL SETTINGS": "GENERAL SETTINGS",
            "DONE": "DONE",
            "CLASSIFICATION": "CLASSIFICATION",
            "MEDIA LIBRARY": "MEDIA LIBRARY",
            "Folders": "Folders",
            "RESET APPLICATION DATA": "RESET APPLICATION DATA",
            "By Album": "By Album",
            "By Artist": "By Artist",
            "COLLECTION": "COLLECTION",
            "ALBUM": "ALBUM",
            "Play All": "Play All",
            "Shuffle": "Shuffle",
            "VIEW FULL ALBUM": "VIEW FULL ALBUM",
            "APPEARANCE": "APPEARANCE",
            "Dark Mode": "Dark Mode",
            "Language": "Language",
            "Add Music Folder": "Add Music Folder",
            "Searching lyrics...": "Searching lyrics...",
            "Lyrics not found": "Lyrics not found",
            "RETRY SEARCH": "RETRY SEARCH",
            "Browse All Music": "Browse All Music",
            "Recently Added": "Recently Added",
            "12 New": "12 New",
            // Search Page
            "Search music...": "Search music...",
            "ALL": "ALL",
            "SONGS": "SONGS",
            "RESULTS": "RESULTS",
            "No results found": "No results found",
            "Type to search your library": "Type to search your library",
            // Queue Page
            "NOW PLAYING": "NOW PLAYING",
            "UP NEXT": "UP NEXT",
            "Clear Queue": "Clear Queue",
            "No tracks in queue": "No tracks in queue",
            // Equalizer Page
            "PRESETS": "PRESETS",
            "Flat": "Flat",
            "Rock": "Rock",
            "Pop": "Pop",
            "Jazz": "Jazz",
            "Classical": "Classical",
            "Bass Boost": "Bass Boost",
            "Treble Boost": "Treble Boost",
            "Custom": "Custom",
            "MASTER": "MASTER",
            "RESET": "RESET",
            "ON": "ON",
            "OFF": "OFF",
        ],
        "zh": [
            "LIBRARY": "媒体库",
            "SEARCH": "搜索",
            "PLAYER": "播放",
            "EQUALIZER": "均衡器",
            "QUEUE": "播放队列",
            "ARTISTS": "艺术家",
            "MY COLLECTION": "我的收藏",
            "SETTINGS": "设置",
            "Interface Language": "界面语言",
            "NOW PLAYING": "正在播放",
            "LYRICS": "歌词",
            "ALBUMS": "专辑",
            "Theme": "主题",
            "Dark": "深色",
            "Light": "浅色",
            "Parse .cue sheets": "解析 .cue 分轨",
            "Search for .lrc lyrics": "搜索 .lrc 歌词",
            "Auto-scan on startup": "启动时自动扫描",
            "Rescan Now": "立即重新扫描",
            "Clear Library": "清空媒体库",
            "MEDIA FOLDERS": "媒体文件夹",
            "SCANNING OPTIONS": "扫描选项",
            "MAINTENANCE": "维护",
            "GENERAL SETTINGS": "常规设置",
            "DONE": "完成",
            "CLASSIFICATION": "分类",
            "MEDIA LIBRARY": "媒体库",
            "Folders": "个文件夹",
            "RESET APPLICATION DATA": "重置应用程序数据",
            "By Album": "按专辑",
            "By Artist": "按艺术家",
            "COLLECTION": "收藏",
            "ALBUM": "专辑",
            "Play All": "全部播放",
            "Shuffle": "随机播放",
            "VIEW FULL ALBUM": "查看完整专辑",
            "APPEARANCE": "外观",
            "Dark Mode": "深色模式",
            "Language": "语言",
            "Add Music Folder": "添加音乐文件夹",
            "Searching lyrics...": "正在搜索歌词...",
            "Lyrics not found": "未找到歌词",
            "RETRY SEARCH": "重试搜索",
            "Browse All Music": "浏览所有音乐",
            "Recently Added": "最近添加",
            "12 New": "12 首新曲",
            // Search Page
            "Search music...": "搜索音乐...",
            "ALL": "全部",
            "SONGS": "歌曲",
            "RESULTS": "搜索结果",
            "No results found": "未找到结果",
            "Type to search your library": "输入关键词搜索媒体库",
            // Queue Page
            "UP NEXT": "即将播放",
            "Clear Queue": "清空队列",
            "No tracks in queue": "队列中没有曲目",
            // Equalizer Page
            "PRESETS": "预设",
            "Flat": "平坦",
            "Rock": "摇滚",
            "Pop": "流行",
            "Jazz": "爵士",
            "Classical": "古典",
            "Bass Boost": "低音增强",
            "Treble Boost": "高音增强",
            "Custom": "自定义",
            "MASTER": "主音量",
            "RESET": "重置",
            "ON": "开",
            "OFF": "关",
        ]
    ]
    
    func t(_ key: String) -> String {
        return translations[language]?[key] ?? key
    }
}

// 🚀 修复：增加 String 扩展，支持原有代码中的 .localized 写法
extension String {
    var localized: String {
        return LocalizationManager.shared.t(self)
    }
}
